[build]
builder = "nixpacks"
buildCommand = """
npm install
cd frontend && npm install && npm run build
cd ../backend && npm install
"""

[deploy]
startCommand = "cd backend && NODE_ENV=production npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 